/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: test/others/unix-callback/unix.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "test/others/unix-callback/unix.pb-c.h"
void   unix_test__init
                     (UnixTest         *message)
{
  static const UnixTest init_value = UNIX_TEST__INIT;
  *message = init_value;
}
size_t unix_test__get_packed_size
                     (const UnixTest *message)
{
  assert(message->base.descriptor == &unix_test__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t unix_test__pack
                     (const UnixTest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &unix_test__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t unix_test__pack_to_buffer
                     (const UnixTest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &unix_test__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UnixTest *
       unix_test__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UnixTest *)
     protobuf_c_message_unpack (&unix_test__descriptor,
                                allocator, len, data);
}
void   unix_test__free_unpacked
                     (UnixTest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &unix_test__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor unix_test__field_descriptors[2] =
{
  {
    "val",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(UnixTest, val),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(UnixTest, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned unix_test__field_indices_by_name[] = {
  1,   /* field[1] = name */
  0,   /* field[0] = val */
};
static const ProtobufCIntRange unix_test__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor unix_test__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "unix_test",
  "UnixTest",
  "UnixTest",
  "",
  sizeof(UnixTest),
  2,
  unix_test__field_descriptors,
  unix_test__field_indices_by_name,
  1,  unix_test__number_ranges,
  (ProtobufCMessageInit) unix_test__init,
  NULL,NULL,NULL    /* reserved[123] */
};
