/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: test/zdtm/static/criu-rtc.proto */

#ifndef PROTOBUF_C_test_2fzdtm_2fstatic_2fcriu_2drtc_2eproto__INCLUDED
#define PROTOBUF_C_test_2fzdtm_2fstatic_2fcriu_2drtc_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _CriuRtc CriuRtc;


/* --- enums --- */


/* --- messages --- */

struct  _CriuRtc
{
  ProtobufCMessage base;
  uint64_t irqp;
};
#define CRIU_RTC__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&criu_rtc__descriptor) \
    , 0 }


/* CriuRtc methods */
void   criu_rtc__init
                     (CriuRtc         *message);
size_t criu_rtc__get_packed_size
                     (const CriuRtc   *message);
size_t criu_rtc__pack
                     (const CriuRtc   *message,
                      uint8_t             *out);
size_t criu_rtc__pack_to_buffer
                     (const CriuRtc   *message,
                      ProtobufCBuffer     *buffer);
CriuRtc *
       criu_rtc__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   criu_rtc__free_unpacked
                     (CriuRtc *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*CriuRtc_Closure)
                 (const CriuRtc *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor criu_rtc__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_test_2fzdtm_2fstatic_2fcriu_2drtc_2eproto__INCLUDED */
