/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: test/zdtm/static/criu-rtc.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "test/zdtm/static/criu-rtc.pb-c.h"
void   criu_rtc__init
                     (CriuRtc         *message)
{
  static const CriuRtc init_value = CRIU_RTC__INIT;
  *message = init_value;
}
size_t criu_rtc__get_packed_size
                     (const CriuRtc *message)
{
  assert(message->base.descriptor == &criu_rtc__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t criu_rtc__pack
                     (const CriuRtc *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &criu_rtc__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t criu_rtc__pack_to_buffer
                     (const CriuRtc *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &criu_rtc__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CriuRtc *
       criu_rtc__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CriuRtc *)
     protobuf_c_message_unpack (&criu_rtc__descriptor,
                                allocator, len, data);
}
void   criu_rtc__free_unpacked
                     (CriuRtc *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &criu_rtc__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor criu_rtc__field_descriptors[1] =
{
  {
    "IRQP",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(CriuRtc, irqp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned criu_rtc__field_indices_by_name[] = {
  0,   /* field[0] = IRQP */
};
static const ProtobufCIntRange criu_rtc__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor criu_rtc__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "criu_rtc",
  "CriuRtc",
  "CriuRtc",
  "",
  sizeof(CriuRtc),
  1,
  criu_rtc__field_descriptors,
  criu_rtc__field_indices_by_name,
  1,  criu_rtc__number_ranges,
  (ProtobufCMessageInit) criu_rtc__init,
  NULL,NULL,NULL    /* reserved[123] */
};
